### ISSUE TITLE
New Switch release maybe?

### ISSUE THREAD

**Issue by rsn8887** [usineur/residualvm#3]
Hello @usineur , I love the last few commits. They make the Switch version much better :) Could you make a new Switch release maybe, if you find some time? Thank you!

**Comment by usineur** [comment]
Hi. Are you talking about the last commits on **switch** branch ?

**Comment by rsn8887** [comment]
yes

**Comment by usineur** [comment]
Ok. I can do that.

**Comment by rsn8887** [comment]
Awesome, thanks! I love your work, by the way, also on SDL pop etc. :)

**Comment by usineur** [comment]
Done.

https://github.com/usineur/residualvm/releases/tag/0.4.0git-2

**Comment by rsn8887** [comment]
Awesome thanks so much!
